### PR TITLE
SCT-1674 Updated KBaseReport clients with kb-sdk:20181203

### PR DESCRIPTION
**Pull request by bio-boris**

### CODE REVIEW

**Comment by bio-boris** [comment]
I think sometimes the test fails with 

```
1545328253.35: uploading file /kb/module/work/tmp/a.txt into shock node
1545328254.22 - CallbackServer[cc241f87-719a-46b0-8ecc-a879b6c5d30d]: "DataFileUtil.file_to_shock" job threw an error, name="Server error", code=-32000, message="", data:
1545328254.22 - CallbackServer[cc241f87-719a-46b0-8ecc-a879b6c5d30d]: Traceback (most recent call last):
1545328254.22 - CallbackServer[cc241f87-719a-46b0-8ecc-a879b6c5d30d]:   File "/kb/module/bin/../lib/DataFileUtil/DataFileUtilServer.py", line 95, in _call_method
1545328254.22 - CallbackServer[cc241f87-719a-46b0-8ecc-a879b6c5d30d]:     result = method(ctx, *params)
1545328254.22 - CallbackServer[cc241f87-719a-46b0-8ecc-a879b6c5d30d]:   File "/kb/module/lib/DataFileUtil/DataFileUtilImpl.py", line 894, in file_to_shock
1545328254.23 - CallbackServer[cc241f87-719a-46b0-8ecc-a879b6c5d30d]:     with open(os.path.abspath(file_path), 'rb') as data_file:
1545328254.23 - CallbackServer[cc241f87-719a-46b0-8ecc-a879b6c5d30d]: IOError: [Errno 2] No such file or directory: u'/kb/module/work/tmp/a.txt'
E
======================================================================
ERROR: test suite for <class 'KBaseReport_server_test.KBaseReportTest'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 208, in run
    self.setUp()
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 291, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 314, in setupContext
    try_run(context, names)
  File "/usr/lib/python2.7/dist-packages/nose/util.py", line 471, in try_run
    return func()
  File "/kb/module/test/KBaseReport_server_test.py", line 65, in setUpClass
    'file_path': cls.a_file_path, 'make_handle': 0
  File "/kb/module/lib/installed_clients/DataFileUtilClient.py", line 163, in file_to_shock
    [params], self._service_ver, context)
  File "/kb/module/lib/installed_clients/baseclient.py", line 253, in run_job
    job_state = self._check_job(mod, job_id)
  File "/kb/module/lib/installed_clients/baseclient.py", line 220, in _check_job
    return self._call(self.url, service + '._check_job', [job_id])
  File "/kb/module/lib/installed_clients/baseclient.py", line 187, in _call
    raise ServerError(**err['error'])
ServerError: Server error: -32000.
Traceback (most recent call last):
  File "/kb/module/bin/../lib/DataFileUtil/DataFileUtilServer.py", line 95, in _call_method
    result = method(ctx, *params)
  File "/kb/module/lib/DataFileUtil/DataFileUtilImpl.py", line 894, in file_to_shock
    with open(os.path.abspath(file_path), 'rb') as data_file:
IOError: [Errno 2] No such file or directory: u'/kb/module/work/tmp/a.txt'
```
But then sometimes all tests pass

**Comment by jayrbolton** [comment]
Diff looks good to me. I'll try running the tests locally.

**Comment by bio-boris** [comment]
@jayrbolton

**Comment by jayrbolton** [comment]
Locally I'm getting `KBaseReport/test_local/run_subjob.sh: line 2: KBaseReport/test_local/run_docker.sh: No such file or directory`. Haven't been able to debug it yet

**Comment by jayrbolton** [comment]
It was because I moved the repo directory at some point. Some auto-generated scripts have hard-coded absolute paths. We should change that some time.

**Comment by jayrbolton** [comment]
Now I'm getting `OSError: [Errno 13] Permission denied: '/kb/module/work/tmp/3768813e-ab85-4752-992f-217e91899cce'`

**Comment by jayrbolton** [comment]
Tests on master are working fine for me.

**Comment by jayrbolton** [comment]
Now your branch is working for me. I had to delete and re-pull the repo from scratch.

**Pull request merged**
